_BASE_: ../../env.yaml
DATASETS:
  TRAIN: ("trainset",)
  TEST: ("valset",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 2400
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 10.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
#  AMP:
#    ENABLED: True
INPUT:
  CROP:
    ENABLED: False
TEST:
  AUG:
    ENABLED: False
  EVAL_PERIOD: 2400
DATALOADER:
  NUM_WORKERS: 4
VERSION: 2
SEED: 0
